kind: pipeline
name: default

steps:
- name: setup
  image: verdaccio/verdaccio:4
  detach: true
  volumes:
    - name: cache
      path: /tmp/cache
    - name: conf
      path: /conf
    - name: storage
      path: /storage
  
volumes:
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  
- name: cache
  temp: {}


trigger:
  event:
  - push
  branch:
  - develop