clone:
  git:
    image: plugins/git
    pull: true
pipeline:
  build:
    name: verdaccio
    image: verdaccio/verdaccio:4
    detach: true
    pull: true
    volumes: [
      "./storage:/verdaccio/storage",
      "./conf:/verdaccio/conf"
    ]
    when:
      event:
      - push


trigger:
  branch:
  - develop