kind: pipeline
name: default

steps:
# - name: setup
#   image: verdaccio/verdaccio:4
#   detach: true
  
- name: deploy
  image: docker/compose:1.19.0
  volumes:
    - name: cache
      path: /tmp/cache
    - name: conf
      path: /conf
    - name: storage
      path: /storage
  command:
    - docker-compose -p verdaccio down
    - docker-compose -p verdaccio up -d
  
volumes:
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  
- name: cache
  temp: {}


trigger:
  event:
  - push
  branch:
  - develop