kind: pipeline
name: default

steps:
- name: verdaccio
  image: verdaccio/verdaccio:4
  detach: true
  volumes:
  - name: conf
    path: /var/local/conf
  - name: storage
    path: /var/local/storage

  command:
    - docker run -it -d -v /var/local/storage:/verdaccio/storage -v /var/local/conf:/verdaccio/conf --name verdaccio -p 4873:4873 --rm verdaccio/verdaccio:4
  
volumes:
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  



trigger:
  event:
  - push
  branch:
  - develop