kind: pipeline
name: default

steps:
- name: deploy
  image: verdaccio/verdaccio:4
  volumes:
    - name: docker
      path: /var/run/docker.sock
    - name: cache
      path: /tmp/cache
    - name: conf
      path: /conf
    - name: storage
      path: /storage
  command:
    - docker run -it -d -v /storage:/verdaccio/storage -v /conf:/verdaccio/conf --name verdaccio -p 4873:4873 --rm verdaccio/verdaccio:4

  

    # - up --help
  
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  
- name: cache
  temp: {}


trigger:
  event:
  - push
  branch:
  - develop