kind: pipeline
name: default

steps:
- name: verdaccio
  image: verdaccio/verdaccio:4
  detach: true
  volumes:
  - name: conf
    path: /verdaccio/conf
  - name: storage
    path: /verdaccio/storage

  command:
    - ls /verdaccio
  
volumes:
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  



trigger:
  event:
  - push
  branch:
  - develop