clone:
  git:
    image: plugins/git
    pull: true
pipeline:
  deploy:
    image: verdaccio/verdaccio:4
    detach: true
  volume:
    - "./storage:/verdaccio/storage"
    - "./conf:/verdaccio/conf"
  when:
    event:
      - push
trigger:
  branch:
  - develop