kind: pipeline
name: default

steps:
- name: deploy
  image: plugin/docker
  detach: true
  volumes:
    - name: conf
      path: /conf
    - name: storage
      path: /storage
  command:
    - docker run -it -v /storage:/verdaccio/storage -v /conf:/verdaccio/conf --name verdaccio -p 4873:4873 --rm verdaccio/verdaccio:4
  
volumes:
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  



trigger:
  event:
  - push
  branch:
  - develop