clone:
  git:
    image: plugins/git
    pull: true
kind: pipeline
name: verdaccio
steps:
- name: deploy
  image: verdaccio/verdaccio:4
  pull: true
  when:
    event:
    - push


trigger:
  branch:
  - develop