kind: pipeline
name: default

steps:
- name: verdaccio
  image: verdaccio/verdaccio:4
  detach: true
  pull: always
- name: deploy
  image: plugins/docker
  command:
  - docker run -it -d -v ${PWD}/storage:/verdaccio/storage -v ${PWD}/conf:/verdaccio/conf --name verdaccio -p 4873:4873 --rm verdaccio/verdaccio:4


trigger:
  event:
  - push
  branch:
  - develop