clone:
  git:
    image: plugins/git
    pull: true
pipeline:
  build:
    image: plugins/docker
    repo: tmaier/docker-compose
    username: paultakku
    password: love0738
    pull: true
    commands:
      - docker-compose up -d
    volume:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event:
      - push
  

# - name: deploy
#   detach: true
#   image: verdaccio/verdaccio:4
  

trigger:
  branch:
  - develop