kind: pipeline
name: default

steps:
- name: deploy
  image: docker/compose:1.19.0
  volumes:
    - name: cache
      path: /tmp/cache
    - name: conf
      path: /conf
    - name: storage
      path: /storage
  command:
    - run -it -d -v /var/local/verdaccio/storage:/verdaccio/storage -v /var/local/verdaccio/conf:/verdaccio/conf --name verdaccio -p 4873:4873 --rm verdaccio/verdaccio:4

  

    # - up --help
  
volumes:
- name: conf
  host: 
    path: /var/local/verdaccio/conf
- name: storage
  host: 
    path: /var/local/verdaccio/storage  
- name: cache
  temp: {}


trigger:
  event:
  - push
  branch:
  - develop