kind: pipeline
name: default

steps:
- name: verdaccio
  image: verdaccio/verdaccio:4
  detach: true
  # volumes:
  #       - "/var/local/verdaccio/storage:/verdaccio/storage"
  #       - "./conf:/verdaccio/conf"
  command:
  - ls /verdaccio
  


trigger:
  event:
  - push
  branch:
  - develop