version: '2.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: verdaccio-docker-local-storage-vol
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
  nginx: 
    image: nginx
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
volumes:
  verdaccio:
    driver: local
  nginx:
    driver: local