version: '2.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - "/var/local/verdaccio/storage:/verdaccio/storage"
      - "/var/local/verdaccio/conf:/verdaccio/conf"